name: Terraform Operations

on:
  push:
    branches:
      - main

jobs:
  setup-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use local install action
        uses: ./.github/actions/install
        with:
          terraform_version: '1.5.7'

      - name: Check Terraform
        run: terraform --version

      - name: Use local terraform operations action
        uses: ./.github/actions/terraform-operations