name: Terraform Operations

on:
  push:
    branches:
      - main

jobs:
  setup-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Use local install action
        uses: ./.github/actions/install
        with:
          terraform_version: '1.5.7'

      - name: Check Terraform
        run: terraform --version